### ISSUE TITLE
Con-PCA Pilot

### ISSUE THREAD

**Issue by zenine07** [cisagov/con-pca-cicd#423]
After the deployment to production completes #422. Initial piloting tests can occur.

Testing Checklist:

- [x] Determine the length of the pilot and the flow rate
- [x] Get a refined set of templates
- [x] Test all templates to make sure everything looks good in the emails.
- [x] Get a domain categorized for the pilot.
- [x] Test emails from the new clean domain to make sure it gets into inboxes.
- [x] Run a test against large amount of users (Probably in staging with a burner domain).
- [x] Create pilot customer in the app.
- [x] Start subscription for pilot customer.

Documentation Checklist
- [x] Data Dictionary
- [x] Data Flow Documentation

New Features that need to be created

- [x] Sending Profile domain for landing page URL.

Paperwork Checklist:

- [x] Confirm Start Date with Customer
- [x] Get new PCA App A signed with Continuous phishing option noted (start date, no end date)
- [x] Receive emails from customer in proper format

**Comment by teal-e** [comment]
Three checklist things on the paperwork side: confirm start date with pilot customer, get new PCA App A signed with Continuous phishing option noted (start date, no end date), and receive emails from customer in proper format

**Comment by zenine07** [comment]
I made updates to the checklist with those paperwork items.
