### ISSUE TITLE
Fine-Grained Permissions

### ISSUE THREAD

**Issue by zenine07** [cisagov/con-pca-cicd#424]
@dav3r requested to fine grain the indivdual permissions for IAM roles to something similar like this - https://github.com/cisagov/cool-assessment-terraform/blob/08cf22ebb0893d9b762a5329097a44f69e4200ff/provisionassessment_policy.tf.

**Comment by dav3r** [comment]
@zenine07 - Can you please point to the PR or commits where these changes were made?  Thanks!

**Comment by zenine07** [comment]
Yes, here is the commit where the changes were made. https://github.com/cisagov/con-pca-cicd/commit/fb025ffb87a17de6d02ee0fac61589ce4fdf8156

You'll see that some of the actions still have "*" for them.  This is because terraform actually needs full permissions for those services. I broke out the ones that really need broke out. If you want me to break them out farther, I will have to generate multiple roles as breaking everything out, puts the document over the character limit.

**Comment by dav3r** [comment]
Excellent- thanks for the clarification.  I don't understand when you say:

> some of the actions still have "*" for them. This is because terraform actually needs full permissions for those services.

But then you mention that you can still break out additional permissions.  Does that mean that some of the "*" permissions can still be further constrained, but you were limited by the document size?

Regarding the policy document size, can't you just split the permissions up into multiple policies and attach them all to the same role (`var.provision_account_role_name`)?  Not sure if that is what you meant, but it sounded like you were talking about multiple roles, not multiple policies.

**Comment by zenine07** [comment]
Oh, sorry, meant multiple policies. 

None of the * permissions can really be further constrained, except by one, maybe two permissions, but those permissions are not really destructive in any way, so I thought for ease, it's better to just put *.

**Comment by dav3r** [comment]
In general, we prefer to spell out exactly what is needed, rather than use the * wildcard.  One main reason is that if AWS adds additional permissions, they don't automatically get included- we have to explicitly add them.  If it's not a huge lift on your end, we would like to have you eliminate the wildcards throughout the policy, even if you have to split them up across multiple policies.

**Comment by zenine07** [comment]
Ok, Will do.

**Comment by zenine07** [comment]
@dav3r Just created this pull request. I don't define each and every permission, but I also don't use wildcard for everything. I requested you as a reviewer, so let me know your thoughts. https://github.com/cisagov/con-pca-cicd/pull/425
